/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thinkaurelius.thrift.test;


public enum ArgType implements org.apache.thrift.TEnum {
  INT(0),
  LONG(1);

  private final int value;

  private ArgType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ArgType findByValue(int value) { 
    switch (value) {
      case 0:
        return INT;
      case 1:
        return LONG;
      default:
        return null;
    }
  }
}
